version: '3.7'
services:
  chromedriver:
    image: blueimp/chromedriver
    init: true
  tests:
    image: 'node:10'
    command: /bin/bash -c 'npm install && npm run test:ci'
    links:
      - chromedriver
    volumes:
      - ./:/app
    working_dir: /app
